class Country {
  final String name;
  final String code;
  final String flag;

  const Country({required this.name, required this.code, required this.flag});
}

const List<Country> countries = [
  Country(name: 'Afghanistan', code: '+93', flag: 'af'),
  Country(name: 'Albania', code: '+355', flag: 'al'),
  Country(name: 'Algeria', code: '+213', flag: 'dz'),
  Country(name: 'Andorra', code: '+376', flag: 'ad'),
  Country(name: 'Angola', code: '+244', flag: 'ao'),
  Country(name: 'Argentina', code: '+54', flag: 'ar'),
  Country(name: 'Armenia', code: '+374', flag: 'am'),
  Country(name: 'Australia', code: '+61', flag: 'au'),
  Country(name: 'Austria', code: '+43', flag: 'at'),
  Country(name: 'Azerbaijan', code: '+994', flag: 'az'),
  Country(name: 'Bahamas', code: '+1-242', flag: 'bs'),
  Country(name: 'Bahrain', code: '+973', flag: 'bh'),
  Country(name: 'Bangladesh', code: '+880', flag: 'bd'),
  Country(name: 'Belgium', code: '+32', flag: 'be'),
  Country(name: 'Brazil', code: '+55', flag: 'br'),
  Country(name: 'Canada', code: '+1', flag: 'ca'),
  Country(name: 'China', code: '+86', flag: 'cn'),
  Country(name: 'Denmark', code: '+45', flag: 'dk'),
  Country(name: 'Egypt', code: '+20', flag: 'eg'),
  Country(name: 'France', code: '+33', flag: 'fr'),
  Country(name: 'Germany', code: '+49', flag: 'de'),
  Country(name: 'Greece', code: '+30', flag: 'gr'),
  Country(name: 'Hong Kong', code: '+852', flag: 'hk'),
  Country(name: 'India', code: '+91', flag: 'in'),
  Country(name: 'Indonesia', code: '+62', flag: 'id'),
  Country(name: 'Iran', code: '+98', flag: 'ir'),
  Country(name: 'Iraq', code: '+964', flag: 'iq'),
  Country(name: 'Ireland', code: '+353', flag: 'ie'),
  Country(name: 'Italy', code: '+39', flag: 'it'),
  Country(name: 'Japan', code: '+81', flag: 'jp'),
  Country(name: 'Jordan', code: '+962', flag: 'jo'),
  Country(name: 'Kuwait', code: '+965', flag: 'kw'),
  Country(name: 'Lebanon', code: '+961', flag: 'lb'),
  Country(name: 'Malaysia', code: '+60', flag: 'my'),
  Country(name: 'Mexico', code: '+52', flag: 'mx'),
  Country(name: 'Netherlands', code: '+31', flag: 'nl'),
  Country(name: 'New Zealand', code: '+64', flag: 'nz'),
  Country(name: 'Norway', code: '+47', flag: 'no'),
  Country(name: 'Oman', code: '+968', flag: 'om'),
  Country(name: 'Pakistan', code: '+92', flag: 'pk'),
  Country(name: 'Philippines', code: '+63', flag: 'ph'),
  Country(name: 'Portugal', code: '+351', flag: 'pt'),
  Country(name: 'Qatar', code: '+974', flag: 'qa'),
  Country(name: 'Russia', code: '+7', flag: 'ru'),
  Country(name: 'Saudi Arabia', code: '+966', flag: 'sa'),
  Country(name: 'Singapore', code: '+65', flag: 'sg'),
  Country(name: 'South Africa', code: '+27', flag: 'za'),
  Country(name: 'South Korea', code: '+82', flag: 'kr'),
  Country(name: 'Spain', code: '+34', flag: 'es'),
  Country(name: 'Sri Lanka', code: '+94', flag: 'lk'),
  Country(name: 'Sweden', code: '+46', flag: 'se'),
  Country(name: 'Switzerland', code: '+41', flag: 'ch'),
  Country(name: 'Thailand', code: '+66', flag: 'th'),
  Country(name: 'Turkey', code: '+90', flag: 'tr'),
  Country(name: 'United Arab Emirates', code: '+971', flag: 'ae'),
  Country(name: 'United Kingdom', code: '+44', flag: 'gb'),
  Country(name: 'United States', code: '+1', flag: 'us'),
  Country(name: 'Vietnam', code: '+84', flag: 'vn'),
];
